server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/productdb
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

